memcached:
  image: memcached:1.6.7
  restart: always
  ports:
    - "11211:11211"
rabbitmq:
  image: rabbitmq:management
  restart: always
  ports:
    - "5672:5672"
    - "15672:15672"
src:
  image: oms/baseimage:%version%
  restart: always
  volumes:
    -  %project_path%:/var/www/oms:rw
    - ./config/nginx.conf:/etc/nginx/sites-enabled/oms.conf
fpm:
  image: oms/fpm:%version%
  restart: always
  volumes_from:
    - src
  environment:
   - XDEBUG_CONFIG="idekey=vscode remote_host=host.docker.internal remote_enable=1 remote_autostart=1"
  links:
    - memcached:memcached
    - rabbitmq:rabbitmq
  ports:
    - "9000:9000"
nginx:
  image: oms/nginx:%version%
  restart: always
  volumes_from:
    - fpm
  links:
    - fpm:fpm
  ports:
    - "8080:80"
